language: node_js
node_js:
  - "4.2"
sudo: false

before_script:
  - npm install -g cordova
  - cordova plugin add cordova-plugin-device
  - cordova platform add browser

script:
  - ./node_modules/.bin/gulp eslint
  - ./node_modules/.bin/gulp test

cache:
  directories:
    - node_modules

addons:
  sauce_connect: true

env:
  global:
    secure: Xn4CvZ6P3Kv1w1I+IzHaQOdy5IeUbhju8KHhSopaa0MRW6fDPMSW1iKjkQvyLK3PQK55OE/YOpo56GvIckvJME7goHczHyT3ErerPzrVh1ZKkF6IHQ+foh3LmKMItHGxW66gJtjxV5eaul47BrYyCii9uIE2GSFVe9sBoxCwtdTWf+goBY7I+3i3NZWfnYORr6q1aPZbQ2qj3X8l22GGR0o2kAK05g2LRZOMxUilp03DW8OuLPlewhp3NLx54kxaMbxl9/Mle0qHEApnI2GFVU9GemQXLCmSevlRQ0uhKrSXMiRXxcqLdu9M0uEMkIDbeYh1DMBmWUGfEtlBtKC0ZRXvyFQnzADOpCV2gXNujWa2C3en9NEpuzctQdebNpIC0vSdnNDvvvDLflwWmfU/wE/l/27VW5mTAod3y3ilT5eEvP5SFF5DO3FxSGuJnjJk1uUzHo8h+v2zleSc+MqHiHdd98ULjahU9WmWyw5LXWcinFzvK0w+6g/69tuVpx1/EaQbUflzxPRTlN28mbUJCqQC5N75RQTEDKjbPI30/uYqu8dLJURdeSSGAdPQDRgSNqRa4f4SG+FKhMkAscZRJV6g8HFjSo8KfM2H56JN8g6gyWh3X1uBEGqFWlWe0dUGVqcwjpRf4baYIPUd1XUny/Iedi5x0wFhWxON+JDVavo=
