language: node_js
node_js:
  - "4.2"
sudo: false

before_script:
  - npm install -g bower
  - bower install
  - npm install -g cordova
  - cordova plugin add cordova-plugin-device
  - cordova platform add browser

script:
  - ./node_modules/.bin/gulp eslint
  - ./node_modules/.bin/gulp test

cache:
  directories:
    - node_modules
    - bower_components

addons:
  sauce_connect: true